import gulp from 'gulp';
import path from 'path';
import fs from 'fs';
import through from 'through2';
import fancyLog from 'fancy-log';
import chalk from 'chalk';
import { config } from '../config.js';

// Helper to flatten nested JSON objects into kebab-case SCSS variables
const flattenTokens = (obj, prefix = '') => {
    let scss = '';
    
    for (const key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key)) {
            const value = obj[key];
            const newPrefix = prefix ? `${prefix}-${key}` : key;

            // Check if it's a value object (Tokens Studio format often uses { value: "...", type: "..." })
            if (typeof value === 'object' && value !== null && 'value' in value) {
                // It's a token!
                let tokenVal = value.value;
                
                // Ensure colors are properly formatted if needed, or refs resolved
                // For this V1, we assume raw values are CSS compatible
                scss += `$${newPrefix.toLowerCase()}: ${tokenVal};\n`;
            } 
            else if (typeof value === 'object' && value !== null) {
                // It's a group, recurse
                scss += flattenTokens(value, newPrefix);
            } 
            else {
                // Raw value mapping
                scss += `$${newPrefix.toLowerCase()}: ${value};\n`;
            }
        }
    }
    return scss;
};

// The Gulp Task
export const tokens = () => {
    return gulp.src(config.paths.src.tokens)
        .pipe(through.obj((file, enc, cb) => {
            if (file.isBuffer()) {
                try {
                    const json = JSON.parse(file.contents.toString());
                    const scssContent = `// -----------------------------------------------------------------------------\n// AUTO-GENERATED FROM FIGMA TOKENS\n// DO NOT EDIT THIS FILE MANUALLY.\n// -----------------------------------------------------------------------------\n\n${flattenTokens(json)}`;
                    
                    // Create a new file object for the SCSS output
                    file.contents = Buffer.from(scssContent);
                    file.path = path.join(path.dirname(file.path), '_generated-tokens.scss');
                    
                    fancyLog(chalk.green(`✔ Converted Figma Tokens: ${path.basename(file.path)}`));
                } catch (e) {
                    fancyLog(chalk.red(`✘ Error parsing JSON token file: ${file.path}`));
                    console.error(e);
                }
            }
            cb(null, file);
        }))
        .pipe(gulp.dest(config.paths.generated.tokens));
};