import gulp from 'gulp';
import path from 'path';
import through from 'through2';
import fancyLog from 'fancy-log';
import chalk from 'chalk';
import { config } from '../config.js';

const genericFontFamilies = new Set([
    'serif',
    'sans-serif',
    'monospace',
    'cursive',
    'fantasy',
    'system-ui',
    'ui-serif',
    'ui-sans-serif',
    'ui-monospace',
    'ui-rounded',
    'emoji',
    'math',
    'fangsong'
]);

const formatTokenValue = (token) => {
    const tokenValue = token.value;

    if (token.type === 'fontFamilies' && typeof tokenValue === 'string') {
        return tokenValue
            .split(',')
            .map((part) => {
                const family = part.trim();
                if (genericFontFamilies.has(family.toLowerCase())) return family.toLowerCase();
                if ((family.startsWith('"') && family.endsWith('"')) || (family.startsWith("'") && family.endsWith("'"))) return family;
                return JSON.stringify(family);
            })
            .join(', ');
    }

    return tokenValue;
};

// Helper to flatten nested JSON objects into kebab-case SCSS variables
const flattenTokens = (obj, prefix = '') => {
    let scss = '';

    for (const key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key)) {
            const value = obj[key];
            const newPrefix = prefix ? `${prefix}-${key}` : key;

            // Tokens Studio values commonly use { value: "...", type: "..." }.
            if (typeof value === 'object' && value !== null && 'value' in value) {
                scss += `$${newPrefix.toLowerCase()}: ${formatTokenValue(value)};\n`;
            }
            else if (typeof value === 'object' && value !== null) {
                scss += flattenTokens(value, newPrefix);
            }
            else {
                scss += `$${newPrefix.toLowerCase()}: ${value};\n`;
            }
        }
    }
    return scss;
};

// The Gulp Task
export const tokens = () => {
    return gulp.src(config.paths.src.tokens)
        .pipe(through.obj((file, enc, cb) => {
            if (file.isBuffer()) {
                try {
                    const json = JSON.parse(file.contents.toString());
                    const scssContent = `// -----------------------------------------------------------------------------\n// AUTO-GENERATED FROM FIGMA TOKENS\n// DO NOT EDIT THIS FILE MANUALLY.\n// -----------------------------------------------------------------------------\n\n${flattenTokens(json)}`;

                    file.contents = Buffer.from(scssContent);
                    file.path = path.join(path.dirname(file.path), '_generated-tokens.scss');

                    fancyLog(chalk.green(`✔ Converted Figma Tokens: ${path.basename(file.path)}`));
                } catch (error) {
                    const message = error instanceof Error ? error.message : String(error);
                    fancyLog(chalk.red(`✘ Error parsing JSON token file: ${file.path}: ${message}`));
                    cb(error);
                    return;
                }
            }
            cb(null, file);
        }))
        .pipe(gulp.dest(config.paths.generated.tokens));
};
